### ISSUE TITLE
Package breaks on DelaunayTriangulation 1.0, and question about code

### ISSUE THREAD

**Issue by DanielVandH** [jonocarroll/TriangulArt.jl#12]
The package currently breaks since on DelaunayTriangulation 1.0 `indices` has now been deleted. I'll get a PR in to fix it.

Also: Just curious, is there a particular reason why `DelaunayTriangulation.jump_and_march` was insufficient for the `which_tri` function? i.e. for 

```julia
function which_tri(trivec::Vector{Vector{Vector{Float64}}}, x::Integer, y::Integer)
    findfirst(z -> 1 == inpolygon((x, y), trivec[z]), 1:length(trivec))
end
```

did `jump_and_march` have issues for you?

**Comment by jonocarroll** [comment]
Thank you! I suppose not having any tests meant that the green light on CI when merging the dependabot PR was somewhat meaningless - definitely my bad on that one.

I can't recall my exact reasoning when I wrote that function; I am new to this space and I was mostly trying to mimic `scipy.spatial.Delaunay.find_simplex` as I was adapting some existing python code. 

Didn't you add `jump_and_march` in the last month or so? I may not have recognised it by this (or its former implementation's) name. I haven't fully explored other options for achieving this but one less dependency sounds great.

I'm checking out that PR now - many thanks!

**Comment by DanielVandH** [comment]
`jump_and_march` has existed since the very beginning of the package almost. It is a bit of a bad name though I'd agree. It was originally called `find_triangle` but then I changed it for some reason (I think because I wanted to add some other methods for point location, which I never even did anyway...). I should change that next time I release a new version..
